//! # Trident Generated Types
//!
//! This file is automatically generated by Trident.
//! **DO NOT EDIT THIS FILE MANUALLY**

#![allow(dead_code)]
#![allow(unused_imports)]

use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use trident_fuzz::fuzzing::*;

// InitializeParams is missing from Trident codegen — define it manually.
// Must match the on-chain struct in programs/sss-core/src/instructions/initialize.rs
#[derive(Debug, Clone, BorshDeserialize, BorshSerialize)]
pub struct InitializeParams {
    pub decimals: u8,
    pub enable_metadata: bool,
    pub name: String,
    pub symbol: String,
    pub uri: String,
    pub additional_metadata: Vec<(String, String)>,
}

// ============================================================================
// PROGRAM MODULES
// ============================================================================

// ----------------------------------------------------------------------------
// Program: sss_transfer_hook
// ----------------------------------------------------------------------------
pub mod sss_transfer_hook {
    use super::*;

    // ------------------------------------------------------------------------
    // Program ID
    // ------------------------------------------------------------------------

    /// Returns the program ID for sss_transfer_hook
    pub fn program_id() -> Pubkey {
        pubkey!("2VymphXYSrCV4qtS3FyiGmNQvcNrEXNUyRUh9MhDTLH9")
    }

    // ------------------------------------------------------------------------
    // Instructions
    // ------------------------------------------------------------------------

    // ....................................................................
    // Instruction: InitializeExtraAccountMetaList
    // ....................................................................

    /// Main instruction struct for InitializeExtraAccountMetaList
    pub struct InitializeExtraAccountMetaListInstruction {
        pub accounts: InitializeExtraAccountMetaListInstructionAccountMetas,
        pub data: InitializeExtraAccountMetaListInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for InitializeExtraAccountMetaList instruction
    #[derive(Debug, Clone, Default)]
    pub struct InitializeExtraAccountMetaListInstructionAccountMetas {
        pub payer: AccountMeta,

        pub extra_account_meta_list: AccountMeta,

        pub mint: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for InitializeExtraAccountMetaList instruction
    #[derive(Debug, Clone)]
    pub struct InitializeExtraAccountMetaListInstructionAccounts {
        pub payer: Pubkey,

        pub extra_account_meta_list: Pubkey,

        pub mint: Pubkey,
    }

    impl InitializeExtraAccountMetaListInstructionAccounts {
        pub fn new(payer: Pubkey, extra_account_meta_list: Pubkey, mint: Pubkey) -> Self {
            Self {
                payer,

                extra_account_meta_list,

                mint,
            }
        }
    }

    /// Instruction data for InitializeExtraAccountMetaList
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct InitializeExtraAccountMetaListInstructionData {}

    impl InitializeExtraAccountMetaListInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for InitializeExtraAccountMetaListInstruction
    impl InitializeExtraAccountMetaListInstruction {
        fn discriminator() -> [u8; 8] {
            [43u8, 34u8, 13u8, 49u8, 167u8, 88u8, 235u8, 235u8]
        }

        pub fn data(data: InitializeExtraAccountMetaListInstructionData) -> Self {
            Self {
                accounts: InitializeExtraAccountMetaListInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(
            mut self,
            accounts: InitializeExtraAccountMetaListInstructionAccounts,
        ) -> Self {
            self.accounts.payer = AccountMeta::new(accounts.payer, true);

            self.accounts.extra_account_meta_list =
                AccountMeta::new(accounts.extra_account_meta_list, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.payer.clone());

            metas.push(self.accounts.extra_account_meta_list.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: TransferHook
    // ....................................................................

    /// Main instruction struct for TransferHook
    pub struct TransferHookInstruction {
        pub accounts: TransferHookInstructionAccountMetas,
        pub data: TransferHookInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for TransferHook instruction
    #[derive(Debug, Clone, Default)]
    pub struct TransferHookInstructionAccountMetas {
        pub source_token: AccountMeta,

        pub mint: AccountMeta,

        pub destination_token: AccountMeta,

        pub owner: AccountMeta,

        pub extra_account_meta_list: AccountMeta,

        pub sss_core_program: AccountMeta,

        pub config: AccountMeta,

        pub source_blacklist_entry: AccountMeta,

        pub dest_blacklist_entry: AccountMeta,
    }

    /// Account pubkeys for TransferHook instruction
    #[derive(Debug, Clone)]
    pub struct TransferHookInstructionAccounts {
        pub source_token: Pubkey,

        pub mint: Pubkey,

        pub destination_token: Pubkey,

        pub owner: Pubkey,

        pub extra_account_meta_list: Pubkey,

        pub sss_core_program: Pubkey,

        pub config: Pubkey,

        pub source_blacklist_entry: Pubkey,

        pub dest_blacklist_entry: Pubkey,
    }

    impl TransferHookInstructionAccounts {
        pub fn new(
            source_token: Pubkey,

            mint: Pubkey,

            destination_token: Pubkey,

            owner: Pubkey,

            extra_account_meta_list: Pubkey,

            sss_core_program: Pubkey,

            config: Pubkey,

            source_blacklist_entry: Pubkey,

            dest_blacklist_entry: Pubkey,
        ) -> Self {
            Self {
                source_token,

                mint,

                destination_token,

                owner,

                extra_account_meta_list,

                sss_core_program,

                config,

                source_blacklist_entry,

                dest_blacklist_entry,
            }
        }
    }

    /// Instruction data for TransferHook
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct TransferHookInstructionData {
        pub _amount: u64,
    }

    impl TransferHookInstructionData {
        pub fn new(_amount: u64) -> Self {
            Self { _amount }
        }
    }

    /// Implementation for TransferHookInstruction
    impl TransferHookInstruction {
        fn discriminator() -> [u8; 8] {
            [105u8, 37u8, 101u8, 197u8, 75u8, 251u8, 102u8, 26u8]
        }

        pub fn data(data: TransferHookInstructionData) -> Self {
            Self {
                accounts: TransferHookInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: TransferHookInstructionAccounts) -> Self {
            self.accounts.source_token = AccountMeta::new_readonly(accounts.source_token, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.destination_token =
                AccountMeta::new_readonly(accounts.destination_token, false);

            self.accounts.owner = AccountMeta::new_readonly(accounts.owner, false);

            self.accounts.extra_account_meta_list =
                AccountMeta::new_readonly(accounts.extra_account_meta_list, false);

            self.accounts.sss_core_program =
                AccountMeta::new_readonly(accounts.sss_core_program, false);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.source_blacklist_entry =
                AccountMeta::new_readonly(accounts.source_blacklist_entry, false);

            self.accounts.dest_blacklist_entry =
                AccountMeta::new_readonly(accounts.dest_blacklist_entry, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.source_token.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.destination_token.clone());

            metas.push(self.accounts.owner.clone());

            metas.push(self.accounts.extra_account_meta_list.clone());

            metas.push(self.accounts.sss_core_program.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.source_blacklist_entry.clone());

            metas.push(self.accounts.dest_blacklist_entry.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ------------------------------------------------------------------------
    // Composite Accounts
    // ------------------------------------------------------------------------
}

// ----------------------------------------------------------------------------
// Program: sss_core
// ----------------------------------------------------------------------------
pub mod sss_core {
    use super::*;

    // ------------------------------------------------------------------------
    // Program ID
    // ------------------------------------------------------------------------

    /// Returns the program ID for sss_core
    pub fn program_id() -> Pubkey {
        pubkey!("YbMgxHu2yUUSEAw3rCvymGGXebExkKahig1nGCwtDMp")
    }

    // ------------------------------------------------------------------------
    // Instructions
    // ------------------------------------------------------------------------

    // ....................................................................
    // Instruction: AcceptAuthority
    // ....................................................................

    /// Main instruction struct for AcceptAuthority
    pub struct AcceptAuthorityInstruction {
        pub accounts: AcceptAuthorityInstructionAccountMetas,
        pub data: AcceptAuthorityInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for AcceptAuthority instruction
    #[derive(Debug, Clone, Default)]
    pub struct AcceptAuthorityInstructionAccountMetas {
        pub new_authority: AccountMeta,

        pub config: AccountMeta,
    }

    /// Account pubkeys for AcceptAuthority instruction
    #[derive(Debug, Clone)]
    pub struct AcceptAuthorityInstructionAccounts {
        pub new_authority: Pubkey,

        pub config: Pubkey,
    }

    impl AcceptAuthorityInstructionAccounts {
        pub fn new(new_authority: Pubkey, config: Pubkey) -> Self {
            Self {
                new_authority,

                config,
            }
        }
    }

    /// Instruction data for AcceptAuthority
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct AcceptAuthorityInstructionData {}

    impl AcceptAuthorityInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for AcceptAuthorityInstruction
    impl AcceptAuthorityInstruction {
        fn discriminator() -> [u8; 8] {
            [107u8, 86u8, 198u8, 91u8, 33u8, 12u8, 107u8, 160u8]
        }

        pub fn data(data: AcceptAuthorityInstructionData) -> Self {
            Self {
                accounts: AcceptAuthorityInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: AcceptAuthorityInstructionAccounts) -> Self {
            self.accounts.new_authority = AccountMeta::new_readonly(accounts.new_authority, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.new_authority.clone());

            metas.push(self.accounts.config.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: BlacklistAddress
    // ....................................................................

    /// Main instruction struct for BlacklistAddress
    pub struct BlacklistAddressInstruction {
        pub accounts: BlacklistAddressInstructionAccountMetas,
        pub data: BlacklistAddressInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for BlacklistAddress instruction
    #[derive(Debug, Clone, Default)]
    pub struct BlacklistAddressInstructionAccountMetas {
        pub authority: AccountMeta,

        pub config: AccountMeta,

        pub blacklist_entry: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for BlacklistAddress instruction
    #[derive(Debug, Clone)]
    pub struct BlacklistAddressInstructionAccounts {
        pub authority: Pubkey,

        pub config: Pubkey,

        pub blacklist_entry: Pubkey,
    }

    impl BlacklistAddressInstructionAccounts {
        pub fn new(authority: Pubkey, config: Pubkey, blacklist_entry: Pubkey) -> Self {
            Self {
                authority,

                config,

                blacklist_entry,
            }
        }
    }

    /// Instruction data for BlacklistAddress
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct BlacklistAddressInstructionData {
        pub address: Pubkey,
    }

    impl BlacklistAddressInstructionData {
        pub fn new(address: Pubkey) -> Self {
            Self { address }
        }
    }

    /// Implementation for BlacklistAddressInstruction
    impl BlacklistAddressInstruction {
        fn discriminator() -> [u8; 8] {
            [53u8, 99u8, 149u8, 238u8, 109u8, 245u8, 181u8, 198u8]
        }

        pub fn data(data: BlacklistAddressInstructionData) -> Self {
            Self {
                accounts: BlacklistAddressInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: BlacklistAddressInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new(accounts.authority, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.blacklist_entry = AccountMeta::new(accounts.blacklist_entry, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.blacklist_entry.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: BurnTokens
    // ....................................................................

    /// Main instruction struct for BurnTokens
    pub struct BurnTokensInstruction {
        pub accounts: BurnTokensInstructionAccountMetas,
        pub data: BurnTokensInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for BurnTokens instruction
    #[derive(Debug, Clone, Default)]
    pub struct BurnTokensInstructionAccountMetas {
        pub minter: AccountMeta,

        pub config: AccountMeta,

        pub minter_info: AccountMeta,

        pub mint: AccountMeta,

        pub token_account: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for BurnTokens instruction
    #[derive(Debug, Clone)]
    pub struct BurnTokensInstructionAccounts {
        pub minter: Pubkey,

        pub config: Pubkey,

        pub minter_info: Pubkey,

        pub mint: Pubkey,

        pub token_account: Pubkey,
    }

    impl BurnTokensInstructionAccounts {
        pub fn new(
            minter: Pubkey,

            config: Pubkey,

            minter_info: Pubkey,

            mint: Pubkey,

            token_account: Pubkey,
        ) -> Self {
            Self {
                minter,

                config,

                minter_info,

                mint,

                token_account,
            }
        }
    }

    /// Instruction data for BurnTokens
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct BurnTokensInstructionData {
        pub amount: u64,
    }

    impl BurnTokensInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for BurnTokensInstruction
    impl BurnTokensInstruction {
        fn discriminator() -> [u8; 8] {
            [76u8, 15u8, 51u8, 254u8, 229u8, 215u8, 121u8, 66u8]
        }

        pub fn data(data: BurnTokensInstructionData) -> Self {
            Self {
                accounts: BurnTokensInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: BurnTokensInstructionAccounts) -> Self {
            self.accounts.minter = AccountMeta::new_readonly(accounts.minter, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.minter_info = AccountMeta::new_readonly(accounts.minter_info, false);

            self.accounts.mint = AccountMeta::new(accounts.mint, false);

            self.accounts.token_account = AccountMeta::new(accounts.token_account, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.minter.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.minter_info.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.token_account.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: FreezeAccount
    // ....................................................................

    /// Main instruction struct for FreezeAccount
    pub struct FreezeAccountInstruction {
        pub accounts: FreezeAccountInstructionAccountMetas,
        pub data: FreezeAccountInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for FreezeAccount instruction
    #[derive(Debug, Clone, Default)]
    pub struct FreezeAccountInstructionAccountMetas {
        pub authority: AccountMeta,

        pub config: AccountMeta,

        pub mint: AccountMeta,

        pub token_account: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for FreezeAccount instruction
    #[derive(Debug, Clone)]
    pub struct FreezeAccountInstructionAccounts {
        pub authority: Pubkey,

        pub config: Pubkey,

        pub mint: Pubkey,

        pub token_account: Pubkey,
    }

    impl FreezeAccountInstructionAccounts {
        pub fn new(authority: Pubkey, config: Pubkey, mint: Pubkey, token_account: Pubkey) -> Self {
            Self {
                authority,

                config,

                mint,

                token_account,
            }
        }
    }

    /// Instruction data for FreezeAccount
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct FreezeAccountInstructionData {}

    impl FreezeAccountInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for FreezeAccountInstruction
    impl FreezeAccountInstruction {
        fn discriminator() -> [u8; 8] {
            [253u8, 75u8, 82u8, 133u8, 167u8, 238u8, 43u8, 130u8]
        }

        pub fn data(data: FreezeAccountInstructionData) -> Self {
            Self {
                accounts: FreezeAccountInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: FreezeAccountInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new_readonly(accounts.authority, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.mint = AccountMeta::new(accounts.mint, false);

            self.accounts.token_account = AccountMeta::new(accounts.token_account, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.token_account.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Initialize
    // ....................................................................

    /// Main instruction struct for Initialize
    pub struct InitializeInstruction {
        pub accounts: InitializeInstructionAccountMetas,
        pub data: InitializeInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Initialize instruction
    #[derive(Debug, Clone, Default)]
    pub struct InitializeInstructionAccountMetas {
        pub authority: AccountMeta,

        pub mint: AccountMeta,

        pub config: AccountMeta,

        pub system_program: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for Initialize instruction
    #[derive(Debug, Clone)]
    pub struct InitializeInstructionAccounts {
        pub authority: Pubkey,

        pub mint: Pubkey,

        pub config: Pubkey,
    }

    impl InitializeInstructionAccounts {
        pub fn new(authority: Pubkey, mint: Pubkey, config: Pubkey) -> Self {
            Self {
                authority,

                mint,

                config,
            }
        }
    }

    /// Instruction data for Initialize
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct InitializeInstructionData {
        pub params: InitializeParams,
    }

    impl InitializeInstructionData {
        pub fn new(params: InitializeParams) -> Self {
            Self { params }
        }
    }

    /// Implementation for InitializeInstruction
    impl InitializeInstruction {
        fn discriminator() -> [u8; 8] {
            [175u8, 175u8, 109u8, 31u8, 13u8, 152u8, 155u8, 237u8]
        }

        pub fn data(data: InitializeInstructionData) -> Self {
            Self {
                accounts: InitializeInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: InitializeInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new(accounts.authority, true);

            self.accounts.mint = AccountMeta::new(accounts.mint, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.system_program.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: MintTokens
    // ....................................................................

    /// Main instruction struct for MintTokens
    pub struct MintTokensInstruction {
        pub accounts: MintTokensInstructionAccountMetas,
        pub data: MintTokensInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for MintTokens instruction
    #[derive(Debug, Clone, Default)]
    pub struct MintTokensInstructionAccountMetas {
        pub minter: AccountMeta,

        pub config: AccountMeta,

        pub minter_info: AccountMeta,

        pub mint: AccountMeta,

        pub token_account: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for MintTokens instruction
    #[derive(Debug, Clone)]
    pub struct MintTokensInstructionAccounts {
        pub minter: Pubkey,

        pub config: Pubkey,

        pub minter_info: Pubkey,

        pub mint: Pubkey,

        pub token_account: Pubkey,
    }

    impl MintTokensInstructionAccounts {
        pub fn new(
            minter: Pubkey,

            config: Pubkey,

            minter_info: Pubkey,

            mint: Pubkey,

            token_account: Pubkey,
        ) -> Self {
            Self {
                minter,

                config,

                minter_info,

                mint,

                token_account,
            }
        }
    }

    /// Instruction data for MintTokens
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct MintTokensInstructionData {
        pub amount: u64,
    }

    impl MintTokensInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for MintTokensInstruction
    impl MintTokensInstruction {
        fn discriminator() -> [u8; 8] {
            [59u8, 132u8, 24u8, 246u8, 122u8, 39u8, 8u8, 243u8]
        }

        pub fn data(data: MintTokensInstructionData) -> Self {
            Self {
                accounts: MintTokensInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: MintTokensInstructionAccounts) -> Self {
            self.accounts.minter = AccountMeta::new_readonly(accounts.minter, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.minter_info = AccountMeta::new(accounts.minter_info, false);

            self.accounts.mint = AccountMeta::new(accounts.mint, false);

            self.accounts.token_account = AccountMeta::new(accounts.token_account, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.minter.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.minter_info.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.token_account.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Pause
    // ....................................................................

    /// Main instruction struct for Pause
    pub struct PauseInstruction {
        pub accounts: PauseInstructionAccountMetas,
        pub data: PauseInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Pause instruction
    #[derive(Debug, Clone, Default)]
    pub struct PauseInstructionAccountMetas {
        pub pauser: AccountMeta,

        pub config: AccountMeta,
    }

    /// Account pubkeys for Pause instruction
    #[derive(Debug, Clone)]
    pub struct PauseInstructionAccounts {
        pub pauser: Pubkey,

        pub config: Pubkey,
    }

    impl PauseInstructionAccounts {
        pub fn new(pauser: Pubkey, config: Pubkey) -> Self {
            Self { pauser, config }
        }
    }

    /// Instruction data for Pause
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct PauseInstructionData {}

    impl PauseInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for PauseInstruction
    impl PauseInstruction {
        fn discriminator() -> [u8; 8] {
            [211u8, 22u8, 221u8, 251u8, 74u8, 121u8, 193u8, 47u8]
        }

        pub fn data(data: PauseInstructionData) -> Self {
            Self {
                accounts: PauseInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: PauseInstructionAccounts) -> Self {
            self.accounts.pauser = AccountMeta::new_readonly(accounts.pauser, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.pauser.clone());

            metas.push(self.accounts.config.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: RemoveFromBlacklist
    // ....................................................................

    /// Main instruction struct for RemoveFromBlacklist
    pub struct RemoveFromBlacklistInstruction {
        pub accounts: RemoveFromBlacklistInstructionAccountMetas,
        pub data: RemoveFromBlacklistInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for RemoveFromBlacklist instruction
    #[derive(Debug, Clone, Default)]
    pub struct RemoveFromBlacklistInstructionAccountMetas {
        pub authority: AccountMeta,

        pub config: AccountMeta,

        pub blacklist_entry: AccountMeta,
    }

    /// Account pubkeys for RemoveFromBlacklist instruction
    #[derive(Debug, Clone)]
    pub struct RemoveFromBlacklistInstructionAccounts {
        pub authority: Pubkey,

        pub config: Pubkey,

        pub blacklist_entry: Pubkey,
    }

    impl RemoveFromBlacklistInstructionAccounts {
        pub fn new(authority: Pubkey, config: Pubkey, blacklist_entry: Pubkey) -> Self {
            Self {
                authority,

                config,

                blacklist_entry,
            }
        }
    }

    /// Instruction data for RemoveFromBlacklist
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct RemoveFromBlacklistInstructionData {
        pub address: Pubkey,
    }

    impl RemoveFromBlacklistInstructionData {
        pub fn new(address: Pubkey) -> Self {
            Self { address }
        }
    }

    /// Implementation for RemoveFromBlacklistInstruction
    impl RemoveFromBlacklistInstruction {
        fn discriminator() -> [u8; 8] {
            [47u8, 105u8, 20u8, 10u8, 165u8, 168u8, 203u8, 219u8]
        }

        pub fn data(data: RemoveFromBlacklistInstructionData) -> Self {
            Self {
                accounts: RemoveFromBlacklistInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: RemoveFromBlacklistInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new(accounts.authority, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.blacklist_entry = AccountMeta::new(accounts.blacklist_entry, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.blacklist_entry.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Seize
    // ....................................................................

    /// Main instruction struct for Seize
    pub struct SeizeInstruction {
        pub accounts: SeizeInstructionAccountMetas,
        pub data: SeizeInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Seize instruction
    #[derive(Debug, Clone, Default)]
    pub struct SeizeInstructionAccountMetas {
        pub authority: AccountMeta,

        pub config: AccountMeta,

        pub mint: AccountMeta,

        pub from: AccountMeta,

        pub treasury: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for Seize instruction
    #[derive(Debug, Clone)]
    pub struct SeizeInstructionAccounts {
        pub authority: Pubkey,

        pub config: Pubkey,

        pub mint: Pubkey,

        pub from: Pubkey,

        pub treasury: Pubkey,
    }

    impl SeizeInstructionAccounts {
        pub fn new(
            authority: Pubkey,

            config: Pubkey,

            mint: Pubkey,

            from: Pubkey,

            treasury: Pubkey,
        ) -> Self {
            Self {
                authority,

                config,

                mint,

                from,

                treasury,
            }
        }
    }

    /// Instruction data for Seize
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct SeizeInstructionData {
        pub amount: u64,
    }

    impl SeizeInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for SeizeInstruction
    impl SeizeInstruction {
        fn discriminator() -> [u8; 8] {
            [129u8, 159u8, 143u8, 31u8, 161u8, 224u8, 241u8, 84u8]
        }

        pub fn data(data: SeizeInstructionData) -> Self {
            Self {
                accounts: SeizeInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: SeizeInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new_readonly(accounts.authority, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.mint = AccountMeta::new(accounts.mint, false);

            self.accounts.from = AccountMeta::new(accounts.from, false);

            self.accounts.treasury = AccountMeta::new(accounts.treasury, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.from.clone());

            metas.push(self.accounts.treasury.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: ThawAccount
    // ....................................................................

    /// Main instruction struct for ThawAccount
    pub struct ThawAccountInstruction {
        pub accounts: ThawAccountInstructionAccountMetas,
        pub data: ThawAccountInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for ThawAccount instruction
    #[derive(Debug, Clone, Default)]
    pub struct ThawAccountInstructionAccountMetas {
        pub authority: AccountMeta,

        pub config: AccountMeta,

        pub mint: AccountMeta,

        pub token_account: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for ThawAccount instruction
    #[derive(Debug, Clone)]
    pub struct ThawAccountInstructionAccounts {
        pub authority: Pubkey,

        pub config: Pubkey,

        pub mint: Pubkey,

        pub token_account: Pubkey,
    }

    impl ThawAccountInstructionAccounts {
        pub fn new(authority: Pubkey, config: Pubkey, mint: Pubkey, token_account: Pubkey) -> Self {
            Self {
                authority,

                config,

                mint,

                token_account,
            }
        }
    }

    /// Instruction data for ThawAccount
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct ThawAccountInstructionData {}

    impl ThawAccountInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for ThawAccountInstruction
    impl ThawAccountInstruction {
        fn discriminator() -> [u8; 8] {
            [115u8, 152u8, 79u8, 213u8, 213u8, 169u8, 184u8, 35u8]
        }

        pub fn data(data: ThawAccountInstructionData) -> Self {
            Self {
                accounts: ThawAccountInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: ThawAccountInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new_readonly(accounts.authority, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.mint = AccountMeta::new(accounts.mint, false);

            self.accounts.token_account = AccountMeta::new(accounts.token_account, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.token_account.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: TransferAuthority
    // ....................................................................

    /// Main instruction struct for TransferAuthority
    pub struct TransferAuthorityInstruction {
        pub accounts: TransferAuthorityInstructionAccountMetas,
        pub data: TransferAuthorityInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for TransferAuthority instruction
    #[derive(Debug, Clone, Default)]
    pub struct TransferAuthorityInstructionAccountMetas {
        pub authority: AccountMeta,

        pub config: AccountMeta,
    }

    /// Account pubkeys for TransferAuthority instruction
    #[derive(Debug, Clone)]
    pub struct TransferAuthorityInstructionAccounts {
        pub authority: Pubkey,

        pub config: Pubkey,
    }

    impl TransferAuthorityInstructionAccounts {
        pub fn new(authority: Pubkey, config: Pubkey) -> Self {
            Self { authority, config }
        }
    }

    /// Instruction data for TransferAuthority
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct TransferAuthorityInstructionData {
        pub new_authority: Pubkey,
    }

    impl TransferAuthorityInstructionData {
        pub fn new(new_authority: Pubkey) -> Self {
            Self { new_authority }
        }
    }

    /// Implementation for TransferAuthorityInstruction
    impl TransferAuthorityInstruction {
        fn discriminator() -> [u8; 8] {
            [48u8, 169u8, 76u8, 72u8, 229u8, 180u8, 55u8, 161u8]
        }

        pub fn data(data: TransferAuthorityInstructionData) -> Self {
            Self {
                accounts: TransferAuthorityInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: TransferAuthorityInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new_readonly(accounts.authority, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.config.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Unpause
    // ....................................................................

    /// Main instruction struct for Unpause
    pub struct UnpauseInstruction {
        pub accounts: UnpauseInstructionAccountMetas,
        pub data: UnpauseInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Unpause instruction
    #[derive(Debug, Clone, Default)]
    pub struct UnpauseInstructionAccountMetas {
        pub pauser: AccountMeta,

        pub config: AccountMeta,
    }

    /// Account pubkeys for Unpause instruction
    #[derive(Debug, Clone)]
    pub struct UnpauseInstructionAccounts {
        pub pauser: Pubkey,

        pub config: Pubkey,
    }

    impl UnpauseInstructionAccounts {
        pub fn new(pauser: Pubkey, config: Pubkey) -> Self {
            Self { pauser, config }
        }
    }

    /// Instruction data for Unpause
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct UnpauseInstructionData {}

    impl UnpauseInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for UnpauseInstruction
    impl UnpauseInstruction {
        fn discriminator() -> [u8; 8] {
            [169u8, 144u8, 4u8, 38u8, 10u8, 141u8, 188u8, 255u8]
        }

        pub fn data(data: UnpauseInstructionData) -> Self {
            Self {
                accounts: UnpauseInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: UnpauseInstructionAccounts) -> Self {
            self.accounts.pauser = AccountMeta::new_readonly(accounts.pauser, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.pauser.clone());

            metas.push(self.accounts.config.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: UpdateMinter
    // ....................................................................

    /// Main instruction struct for UpdateMinter
    pub struct UpdateMinterInstruction {
        pub accounts: UpdateMinterInstructionAccountMetas,
        pub data: UpdateMinterInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for UpdateMinter instruction
    #[derive(Debug, Clone, Default)]
    pub struct UpdateMinterInstructionAccountMetas {
        pub authority: AccountMeta,

        pub config: AccountMeta,

        pub minter_info: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for UpdateMinter instruction
    #[derive(Debug, Clone)]
    pub struct UpdateMinterInstructionAccounts {
        pub authority: Pubkey,

        pub config: Pubkey,

        pub minter_info: Pubkey,
    }

    impl UpdateMinterInstructionAccounts {
        pub fn new(authority: Pubkey, config: Pubkey, minter_info: Pubkey) -> Self {
            Self {
                authority,

                config,

                minter_info,
            }
        }
    }

    /// Instruction data for UpdateMinter
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct UpdateMinterInstructionData {
        pub minter_address: Pubkey,

        pub quota: u64,

        pub active: bool,
    }

    impl UpdateMinterInstructionData {
        pub fn new(minter_address: Pubkey, quota: u64, active: bool) -> Self {
            Self {
                minter_address,

                quota,

                active,
            }
        }
    }

    /// Implementation for UpdateMinterInstruction
    impl UpdateMinterInstruction {
        fn discriminator() -> [u8; 8] {
            [164u8, 129u8, 164u8, 88u8, 75u8, 29u8, 91u8, 38u8]
        }

        pub fn data(data: UpdateMinterInstructionData) -> Self {
            Self {
                accounts: UpdateMinterInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: UpdateMinterInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new(accounts.authority, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.minter_info = AccountMeta::new(accounts.minter_info, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.minter_info.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: UpdateRoles
    // ....................................................................

    /// Main instruction struct for UpdateRoles
    pub struct UpdateRolesInstruction {
        pub accounts: UpdateRolesInstructionAccountMetas,
        pub data: UpdateRolesInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for UpdateRoles instruction
    #[derive(Debug, Clone, Default)]
    pub struct UpdateRolesInstructionAccountMetas {
        pub authority: AccountMeta,

        pub config: AccountMeta,
    }

    /// Account pubkeys for UpdateRoles instruction
    #[derive(Debug, Clone)]
    pub struct UpdateRolesInstructionAccounts {
        pub authority: Pubkey,

        pub config: Pubkey,
    }

    impl UpdateRolesInstructionAccounts {
        pub fn new(authority: Pubkey, config: Pubkey) -> Self {
            Self { authority, config }
        }
    }

    /// Instruction data for UpdateRoles
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct UpdateRolesInstructionData {
        pub new_pauser: Pubkey,
    }

    impl UpdateRolesInstructionData {
        pub fn new(new_pauser: Pubkey) -> Self {
            Self { new_pauser }
        }
    }

    /// Implementation for UpdateRolesInstruction
    impl UpdateRolesInstruction {
        fn discriminator() -> [u8; 8] {
            [220u8, 152u8, 205u8, 233u8, 177u8, 123u8, 219u8, 125u8]
        }

        pub fn data(data: UpdateRolesInstructionData) -> Self {
            Self {
                accounts: UpdateRolesInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: UpdateRolesInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new_readonly(accounts.authority, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.config.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ------------------------------------------------------------------------
    // Composite Accounts
    // ------------------------------------------------------------------------
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

/// Custom struct: AccountFrozen
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct AccountFrozen {
    pub mint: Pubkey,

    pub account: Pubkey,

    pub authority: Pubkey,
}

impl AccountFrozen {
    pub fn new(mint: Pubkey, account: Pubkey, authority: Pubkey) -> Self {
        Self {
            mint,

            account,

            authority,
        }
    }
}

/// Custom struct: AccountThawed
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct AccountThawed {
    pub mint: Pubkey,

    pub account: Pubkey,

    pub authority: Pubkey,
}

impl AccountThawed {
    pub fn new(mint: Pubkey, account: Pubkey, authority: Pubkey) -> Self {
        Self {
            mint,

            account,

            authority,
        }
    }
}

/// Custom struct: AddedToBlacklist
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct AddedToBlacklist {
    pub mint: Pubkey,

    pub address: Pubkey,
}

impl AddedToBlacklist {
    pub fn new(mint: Pubkey, address: Pubkey) -> Self {
        Self { mint, address }
    }
}

/// Custom struct: AuthorityTransferAccepted
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct AuthorityTransferAccepted {
    pub mint: Pubkey,

    pub old_authority: Pubkey,

    pub new_authority: Pubkey,
}

impl AuthorityTransferAccepted {
    pub fn new(mint: Pubkey, old_authority: Pubkey, new_authority: Pubkey) -> Self {
        Self {
            mint,

            old_authority,

            new_authority,
        }
    }
}

/// Custom struct: AuthorityTransferProposed
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct AuthorityTransferProposed {
    pub mint: Pubkey,

    pub current_authority: Pubkey,

    pub proposed_authority: Pubkey,
}

impl AuthorityTransferProposed {
    pub fn new(mint: Pubkey, current_authority: Pubkey, proposed_authority: Pubkey) -> Self {
        Self {
            mint,

            current_authority,

            proposed_authority,
        }
    }
}

/// Custom struct: BlacklistEntry
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct BlacklistEntry {
    pub config: Pubkey,

    pub address: Pubkey,

    pub bump: u8,
}

impl BlacklistEntry {
    pub fn new(config: Pubkey, address: Pubkey, bump: u8) -> Self {
        Self {
            config,

            address,

            bump,
        }
    }
}

/// Custom struct: Initialized
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct Initialized {
    pub mint: Pubkey,

    pub authority: Pubkey,

    pub name: String,

    pub symbol: String,

    pub decimals: u8,

    pub has_metadata: bool,
}

impl Initialized {
    pub fn new(
        mint: Pubkey,

        authority: Pubkey,

        name: String,

        symbol: String,

        decimals: u8,

        has_metadata: bool,
    ) -> Self {
        Self {
            mint,

            authority,

            name,

            symbol,

            decimals,

            has_metadata,
        }
    }
}

/// Custom struct: MinterInfo
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct MinterInfo {
    pub config: Pubkey,

    pub minter: Pubkey,

    pub quota: u64,

    pub minted: u64,

    pub active: bool,

    pub bump: u8,
}

impl MinterInfo {
    pub fn new(
        config: Pubkey,

        minter: Pubkey,

        quota: u64,

        minted: u64,

        active: bool,

        bump: u8,
    ) -> Self {
        Self {
            config,

            minter,

            quota,

            minted,

            active,

            bump,
        }
    }
}

/// Custom struct: Paused
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct Paused {
    pub mint: Pubkey,

    pub pauser: Pubkey,
}

impl Paused {
    pub fn new(mint: Pubkey, pauser: Pubkey) -> Self {
        Self { mint, pauser }
    }
}

/// Custom struct: RemovedFromBlacklist
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct RemovedFromBlacklist {
    pub mint: Pubkey,

    pub address: Pubkey,
}

impl RemovedFromBlacklist {
    pub fn new(mint: Pubkey, address: Pubkey) -> Self {
        Self { mint, address }
    }
}

/// Custom struct: RolesUpdated
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct RolesUpdated {
    pub mint: Pubkey,

    pub old_pauser: Pubkey,

    pub new_pauser: Pubkey,
}

impl RolesUpdated {
    pub fn new(mint: Pubkey, old_pauser: Pubkey, new_pauser: Pubkey) -> Self {
        Self {
            mint,

            old_pauser,

            new_pauser,
        }
    }
}

/// Custom struct: StablecoinConfig
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct StablecoinConfig {
    pub authority: Pubkey,

    pub mint: Pubkey,

    pub pauser: Pubkey,

    pub pending_authority: Option<Pubkey>,

    pub decimals: u8,

    pub is_paused: bool,

    pub has_metadata: bool,

    pub total_minters: u8,

    pub enable_permanent_delegate: bool,

    pub enable_transfer_hook: bool,

    pub default_account_frozen: bool,

    pub bump: u8,

    pub _reserved: [u8; 128],
}

impl StablecoinConfig {
    pub fn new(
        authority: Pubkey,

        mint: Pubkey,

        pauser: Pubkey,

        pending_authority: Option<Pubkey>,

        decimals: u8,

        is_paused: bool,

        has_metadata: bool,

        total_minters: u8,

        enable_permanent_delegate: bool,

        enable_transfer_hook: bool,

        default_account_frozen: bool,

        bump: u8,

        _reserved: [u8; 128],
    ) -> Self {
        Self {
            authority,

            mint,

            pauser,

            pending_authority,

            decimals,

            is_paused,

            has_metadata,

            total_minters,

            enable_permanent_delegate,

            enable_transfer_hook,

            default_account_frozen,

            bump,

            _reserved,
        }
    }
}

/// Custom struct: TokensBurned
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct TokensBurned {
    pub mint: Pubkey,

    pub minter: Pubkey,

    pub amount: u64,
}

impl TokensBurned {
    pub fn new(mint: Pubkey, minter: Pubkey, amount: u64) -> Self {
        Self {
            mint,

            minter,

            amount,
        }
    }
}

/// Custom struct: TokensMinted
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct TokensMinted {
    pub mint: Pubkey,

    pub minter: Pubkey,

    pub recipient: Pubkey,

    pub amount: u64,
}

impl TokensMinted {
    pub fn new(mint: Pubkey, minter: Pubkey, recipient: Pubkey, amount: u64) -> Self {
        Self {
            mint,

            minter,

            recipient,

            amount,
        }
    }
}

/// Custom struct: TokensSeized
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct TokensSeized {
    pub mint: Pubkey,

    pub from: Pubkey,

    pub treasury: Pubkey,

    pub amount: u64,
}

impl TokensSeized {
    pub fn new(mint: Pubkey, from: Pubkey, treasury: Pubkey, amount: u64) -> Self {
        Self {
            mint,

            from,

            treasury,

            amount,
        }
    }
}

/// Custom struct: Unpaused
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct Unpaused {
    pub mint: Pubkey,

    pub pauser: Pubkey,
}

impl Unpaused {
    pub fn new(mint: Pubkey, pauser: Pubkey) -> Self {
        Self { mint, pauser }
    }
}

/// Custom struct: UpdatedMinter
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct UpdatedMinter {
    pub mint: Pubkey,

    pub minter_address: Pubkey,

    pub active: bool,

    pub quota: u64,
}

impl UpdatedMinter {
    pub fn new(mint: Pubkey, minter_address: Pubkey, active: bool, quota: u64) -> Self {
        Self {
            mint,

            minter_address,

            active,

            quota,
        }
    }
}

// ============================================================================
// END OF GENERATED FILE
// ============================================================================
